g++ main.cpp inf.cpp io.cpp  -march=native -lgsl -lgslcblas -o mpl
./mpl -d ../data/simulation -i jobs/sequences/example-0_ns1000_dt1.dat -o jobs/outputnoRC/sc-0.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-0.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-1_ns1000_dt1.dat -o jobs/outputnoRC/sc-1.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-1.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-2_ns1000_dt1.dat -o jobs/outputnoRC/sc-2.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-2.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-3_ns1000_dt1.dat -o jobs/outputnoRC/sc-3.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-3.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-4_ns1000_dt1.dat -o jobs/outputnoRC/sc-4.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-4.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-5_ns1000_dt1.dat -o jobs/outputnoRC/sc-5.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-5.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-6_ns1000_dt1.dat -o jobs/outputnoRC/sc-6.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-6.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-7_ns1000_dt1.dat -o jobs/outputnoRC/sc-7.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-7.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-8_ns1000_dt1.dat -o jobs/outputnoRC/sc-8.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-8.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-9_ns1000_dt1.dat -o jobs/outputnoRC/sc-9.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-9.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-10_ns1000_dt1.dat -o jobs/outputnoRC/sc-10.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-10.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-11_ns1000_dt1.dat -o jobs/outputnoRC/sc-11.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-11.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-12_ns1000_dt1.dat -o jobs/outputnoRC/sc-12.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-12.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-13_ns1000_dt1.dat -o jobs/outputnoRC/sc-13.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-13.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-14_ns1000_dt1.dat -o jobs/outputnoRC/sc-14.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-14.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-15_ns1000_dt1.dat -o jobs/outputnoRC/sc-15.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-15.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-16_ns1000_dt1.dat -o jobs/outputnoRC/sc-16.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-16.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-17_ns1000_dt1.dat -o jobs/outputnoRC/sc-17.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-17.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-18_ns1000_dt1.dat -o jobs/outputnoRC/sc-18.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-18.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-19_ns1000_dt1.dat -o jobs/outputnoRC/sc-19.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-19.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-20_ns1000_dt1.dat -o jobs/outputnoRC/sc-20.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-20.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-21_ns1000_dt1.dat -o jobs/outputnoRC/sc-21.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-21.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-22_ns1000_dt1.dat -o jobs/outputnoRC/sc-22.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-22.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-23_ns1000_dt1.dat -o jobs/outputnoRC/sc-23.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-23.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-24_ns1000_dt1.dat -o jobs/outputnoRC/sc-24.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-24.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-25_ns1000_dt1.dat -o jobs/outputnoRC/sc-25.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-25.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-26_ns1000_dt1.dat -o jobs/outputnoRC/sc-26.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-26.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-27_ns1000_dt1.dat -o jobs/outputnoRC/sc-27.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-27.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-28_ns1000_dt1.dat -o jobs/outputnoRC/sc-28.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-28.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-29_ns1000_dt1.dat -o jobs/outputnoRC/sc-29.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-29.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-30_ns1000_dt1.dat -o jobs/outputnoRC/sc-30.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-30.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-31_ns1000_dt1.dat -o jobs/outputnoRC/sc-31.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-31.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-32_ns1000_dt1.dat -o jobs/outputnoRC/sc-32.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-32.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-33_ns1000_dt1.dat -o jobs/outputnoRC/sc-33.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-33.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-34_ns1000_dt1.dat -o jobs/outputnoRC/sc-34.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-34.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-35_ns1000_dt1.dat -o jobs/outputnoRC/sc-35.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-35.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-36_ns1000_dt1.dat -o jobs/outputnoRC/sc-36.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-36.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-37_ns1000_dt1.dat -o jobs/outputnoRC/sc-37.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-37.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-38_ns1000_dt1.dat -o jobs/outputnoRC/sc-38.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-38.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-39_ns1000_dt1.dat -o jobs/outputnoRC/sc-39.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-39.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-40_ns1000_dt1.dat -o jobs/outputnoRC/sc-40.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-40.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-41_ns1000_dt1.dat -o jobs/outputnoRC/sc-41.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-41.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-42_ns1000_dt1.dat -o jobs/outputnoRC/sc-42.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-42.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-43_ns1000_dt1.dat -o jobs/outputnoRC/sc-43.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-43.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-44_ns1000_dt1.dat -o jobs/outputnoRC/sc-44.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-44.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-45_ns1000_dt1.dat -o jobs/outputnoRC/sc-45.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-45.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-46_ns1000_dt1.dat -o jobs/outputnoRC/sc-46.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-46.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-47_ns1000_dt1.dat -o jobs/outputnoRC/sc-47.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-47.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-48_ns1000_dt1.dat -o jobs/outputnoRC/sc-48.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-48.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-49_ns1000_dt1.dat -o jobs/outputnoRC/sc-49.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-49.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-50_ns1000_dt1.dat -o jobs/outputnoRC/sc-50.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-50.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-51_ns1000_dt1.dat -o jobs/outputnoRC/sc-51.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-51.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-52_ns1000_dt1.dat -o jobs/outputnoRC/sc-52.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-52.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-53_ns1000_dt1.dat -o jobs/outputnoRC/sc-53.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-53.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-54_ns1000_dt1.dat -o jobs/outputnoRC/sc-54.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-54.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-55_ns1000_dt1.dat -o jobs/outputnoRC/sc-55.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-55.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-56_ns1000_dt1.dat -o jobs/outputnoRC/sc-56.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-56.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-57_ns1000_dt1.dat -o jobs/outputnoRC/sc-57.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-57.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-58_ns1000_dt1.dat -o jobs/outputnoRC/sc-58.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-58.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-59_ns1000_dt1.dat -o jobs/outputnoRC/sc-59.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-59.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-60_ns1000_dt1.dat -o jobs/outputnoRC/sc-60.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-60.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-61_ns1000_dt1.dat -o jobs/outputnoRC/sc-61.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-61.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-62_ns1000_dt1.dat -o jobs/outputnoRC/sc-62.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-62.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-63_ns1000_dt1.dat -o jobs/outputnoRC/sc-63.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-63.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-64_ns1000_dt1.dat -o jobs/outputnoRC/sc-64.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-64.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-65_ns1000_dt1.dat -o jobs/outputnoRC/sc-65.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-65.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-66_ns1000_dt1.dat -o jobs/outputnoRC/sc-66.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-66.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-67_ns1000_dt1.dat -o jobs/outputnoRC/sc-67.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-67.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-68_ns1000_dt1.dat -o jobs/outputnoRC/sc-68.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-68.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-69_ns1000_dt1.dat -o jobs/outputnoRC/sc-69.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-69.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-70_ns1000_dt1.dat -o jobs/outputnoRC/sc-70.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-70.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-71_ns1000_dt1.dat -o jobs/outputnoRC/sc-71.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-71.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-72_ns1000_dt1.dat -o jobs/outputnoRC/sc-72.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-72.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-73_ns1000_dt1.dat -o jobs/outputnoRC/sc-73.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-73.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-74_ns1000_dt1.dat -o jobs/outputnoRC/sc-74.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-74.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-75_ns1000_dt1.dat -o jobs/outputnoRC/sc-75.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-75.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-76_ns1000_dt1.dat -o jobs/outputnoRC/sc-76.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-76.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-77_ns1000_dt1.dat -o jobs/outputnoRC/sc-77.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-77.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-78_ns1000_dt1.dat -o jobs/outputnoRC/sc-78.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-78.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-79_ns1000_dt1.dat -o jobs/outputnoRC/sc-79.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-79.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-80_ns1000_dt1.dat -o jobs/outputnoRC/sc-80.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-80.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-81_ns1000_dt1.dat -o jobs/outputnoRC/sc-81.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-81.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-82_ns1000_dt1.dat -o jobs/outputnoRC/sc-82.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-82.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-83_ns1000_dt1.dat -o jobs/outputnoRC/sc-83.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-83.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-84_ns1000_dt1.dat -o jobs/outputnoRC/sc-84.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-84.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-85_ns1000_dt1.dat -o jobs/outputnoRC/sc-85.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-85.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-86_ns1000_dt1.dat -o jobs/outputnoRC/sc-86.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-86.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-87_ns1000_dt1.dat -o jobs/outputnoRC/sc-87.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-87.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-88_ns1000_dt1.dat -o jobs/outputnoRC/sc-88.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-88.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-89_ns1000_dt1.dat -o jobs/outputnoRC/sc-89.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-89.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-90_ns1000_dt1.dat -o jobs/outputnoRC/sc-90.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-90.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-91_ns1000_dt1.dat -o jobs/outputnoRC/sc-91.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-91.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-92_ns1000_dt1.dat -o jobs/outputnoRC/sc-92.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-92.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-93_ns1000_dt1.dat -o jobs/outputnoRC/sc-93.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-93.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-94_ns1000_dt1.dat -o jobs/outputnoRC/sc-94.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-94.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-95_ns1000_dt1.dat -o jobs/outputnoRC/sc-95.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-95.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-96_ns1000_dt1.dat -o jobs/outputnoRC/sc-96.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-96.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-97_ns1000_dt1.dat -o jobs/outputnoRC/sc-97.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-97.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-98_ns1000_dt1.dat -o jobs/outputnoRC/sc-98.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-98.dat -es traitseq.dat
./mpl -d ../data/simulation -i jobs/sequences/example-99_ns1000_dt1.dat -o jobs/outputnoRC/sc-99.dat -g 1 -N 1e3 -mu 2e-4 -rr 2e-4 -q 2 -e jobs/traitsites/traitsites-99.dat -es traitseq.dat
